services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_PROFILE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/komanda
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456789
      SPRING_DATA_REDIS_HOST: host.docker.internal
      SPRING_DATA_REDIS_PORT: 6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
